name = "Packwiz Mega Modpack [Latest]"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bb2f468e7cbfdd8256cdb7310608f015ca809b6ca61effc150e72666b40b71b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
