name = "Packwiz Mega Modpack [Latest]"
author = "womble"
version = "1.7.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dfa3284ffde7d5a5eb7cc8eb2bc0856055f71fc64d12b096ca0b17f17724a23"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
