name = "Packwiz Mega Modpack [Latest]"
author = "womble"
version = "1.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "510163cc6861467aae6ab95ea49068b2b6072480a47d2d78da5997ee6c4060b5"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
