name = "Packwiz Mega Modpack [Latest]"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caca887ccd35f5ae685f04243019a5c18ac7dca65068b8ebc6f3dbd0a27d1563"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
