name = "Packwiz Mega Modpack [Latest]"
author = "womble"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec1e7c34e9f4968c712736841bb326f0eae1914ca5a9b25f1c9db17169883239"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
